name: ROS2_FOXY_TEST

on:
    workflow_dispatch:
    push:
        branches:
            - master
            - 'releases/**'

jobs:
    job_1:
        runs-on: ubuntu-latest
        name: A test job for ros integration test action
        container: ros:foxy-ros-core
        steps:
            - name: Install Git
              run: |
                  apt-get update
                  apt-get install -y git
              shell: bash
            - uses: actions/checkout@v2
              with:
                submodules: true

            - name: Install dependencies
              run: |
                  apt-get install -y python3-rosdep
                  rosdep init
                  rosdep update
                  cd ~/ros2_ws/src
                  rosdep install -r -y --from-paths . --ignore-src
              shell: bash